<?php return array (
  'table' => 
  array (
    'hd_a' => 
    array (
      'tablename' => 'hd_a',
      'engine' => 'InnoDB',
      'rows' => '180',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 200,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_article' => 
    array (
      'tablename' => 'hd_article',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_article_category' => 
    array (
      'tablename' => 'hd_article_category',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_balance' => 
    array (
      'tablename' => 'hd_balance',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_button' => 
    array (
      'tablename' => 'hd_button',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_cache' => 
    array (
      'tablename' => 'hd_cache',
      'engine' => 'MyISAM',
      'rows' => '5',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '0',
      'indexSize' => '3072',
      'dataSize' => '13976',
      'totalSize' => 17048,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_cloud' => 
    array (
      'tablename' => 'hd_cloud',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_config' => 
    array (
      'tablename' => 'hd_config',
      'engine' => 'InnoDB',
      'rows' => '1',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_core_attachment' => 
    array (
      'tablename' => 'hd_core_attachment',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '65536',
      'dataSize' => '16384',
      'totalSize' => 9519104,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_core_cache' => 
    array (
      'tablename' => 'hd_core_cache',
      'engine' => 'InnoDB',
      'rows' => '4',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '163840',
      'totalSize' => 9601024,
      'first' => 40,
      'fileId' => 2,
      'complete' => true,
    ),
    'hd_core_config' => 
    array (
      'tablename' => 'hd_core_config',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_core_session' => 
    array (
      'tablename' => 'hd_core_session',
      'engine' => 'InnoDB',
      'rows' => '71',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 100,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_credits_record' => 
    array (
      'tablename' => 'hd_credits_record',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '49152',
      'dataSize' => '16384',
      'totalSize' => 9502720,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_material' => 
    array (
      'tablename' => 'hd_material',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_member' => 
    array (
      'tablename' => 'hd_member',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_member_address' => 
    array (
      'tablename' => 'hd_member_address',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_member_fields' => 
    array (
      'tablename' => 'hd_member_fields',
      'engine' => 'InnoDB',
      'rows' => '189',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '16384',
      'dataSize' => '16384',
      'totalSize' => 9469952,
      'first' => 220,
      'fileId' => 2,
      'complete' => true,
    ),
    'hd_member_group' => 
    array (
      'tablename' => 'hd_member_group',
      'engine' => 'InnoDB',
      'rows' => '10',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '16384',
      'dataSize' => '16384',
      'totalSize' => 9469952,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_menu' => 
    array (
      'tablename' => 'hd_menu',
      'engine' => 'InnoDB',
      'rows' => '39',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 60,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_migrations' => 
    array (
      'tablename' => 'hd_migrations',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_module_setting' => 
    array (
      'tablename' => 'hd_module_setting',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '16384',
      'dataSize' => '16384',
      'totalSize' => 9469952,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_modules' => 
    array (
      'tablename' => 'hd_modules',
      'engine' => 'InnoDB',
      'rows' => '11',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_modules_bindings' => 
    array (
      'tablename' => 'hd_modules_bindings',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_package' => 
    array (
      'tablename' => 'hd_package',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_pay' => 
    array (
      'tablename' => 'hd_pay',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_profile_fields' => 
    array (
      'tablename' => 'hd_profile_fields',
      'engine' => 'InnoDB',
      'rows' => '21',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 60,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_reply_basic' => 
    array (
      'tablename' => 'hd_reply_basic',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_reply_cover' => 
    array (
      'tablename' => 'hd_reply_cover',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_reply_image' => 
    array (
      'tablename' => 'hd_reply_image',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_reply_news' => 
    array (
      'tablename' => 'hd_reply_news',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_rule' => 
    array (
      'tablename' => 'hd_rule',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '16384',
      'dataSize' => '16384',
      'totalSize' => 9469952,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_rule_keyword' => 
    array (
      'tablename' => 'hd_rule_keyword',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_site' => 
    array (
      'tablename' => 'hd_site',
      'engine' => 'InnoDB',
      'rows' => '2',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '16384',
      'dataSize' => '16384',
      'totalSize' => 9469952,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_site_modules' => 
    array (
      'tablename' => 'hd_site_modules',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '16384',
      'dataSize' => '16384',
      'totalSize' => 9469952,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_site_package' => 
    array (
      'tablename' => 'hd_site_package',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '16384',
      'dataSize' => '16384',
      'totalSize' => 9469952,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_site_setting' => 
    array (
      'tablename' => 'hd_site_setting',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '16384',
      'dataSize' => '16384',
      'totalSize' => 9469952,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_site_template' => 
    array (
      'tablename' => 'hd_site_template',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '16384',
      'dataSize' => '16384',
      'totalSize' => 9469952,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_site_user' => 
    array (
      'tablename' => 'hd_site_user',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_site_wechat' => 
    array (
      'tablename' => 'hd_site_wechat',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '16384',
      'dataSize' => '16384',
      'totalSize' => 9469952,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_template' => 
    array (
      'tablename' => 'hd_template',
      'engine' => 'InnoDB',
      'rows' => '1',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_ticket' => 
    array (
      'tablename' => 'hd_ticket',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '16384',
      'dataSize' => '16384',
      'totalSize' => 9469952,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_ticket_groups' => 
    array (
      'tablename' => 'hd_ticket_groups',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '49152',
      'dataSize' => '16384',
      'totalSize' => 9502720,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_ticket_module' => 
    array (
      'tablename' => 'hd_ticket_module',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_ticket_record' => 
    array (
      'tablename' => 'hd_ticket_record',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '65536',
      'dataSize' => '16384',
      'totalSize' => 9519104,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_user' => 
    array (
      'tablename' => 'hd_user',
      'engine' => 'InnoDB',
      'rows' => '3',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_user_group' => 
    array (
      'tablename' => 'hd_user_group',
      'engine' => 'InnoDB',
      'rows' => '1',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '0',
      'dataSize' => '16384',
      'totalSize' => 9453568,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_user_permission' => 
    array (
      'tablename' => 'hd_user_permission',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '49152',
      'dataSize' => '16384',
      'totalSize' => 9502720,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_user_profile' => 
    array (
      'tablename' => 'hd_user_profile',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '16384',
      'dataSize' => '16384',
      'totalSize' => 9469952,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_web' => 
    array (
      'tablename' => 'hd_web',
      'engine' => 'InnoDB',
      'rows' => '1',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 40,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_web_article' => 
    array (
      'tablename' => 'hd_web_article',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_web_category' => 
    array (
      'tablename' => 'hd_web_category',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_web_nav' => 
    array (
      'tablename' => 'hd_web_nav',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '49152',
      'dataSize' => '16384',
      'totalSize' => 9502720,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_web_page' => 
    array (
      'tablename' => 'hd_web_page',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
    'hd_web_slide' => 
    array (
      'tablename' => 'hd_web_slide',
      'engine' => 'InnoDB',
      'rows' => '0',
      'collation' => 'utf8_general_ci',
      'charset' => 'utf8',
      'dataFree' => '9437184',
      'indexSize' => '32768',
      'dataSize' => '16384',
      'totalSize' => 9486336,
      'first' => 20,
      'fileId' => 1,
      'complete' => true,
    ),
  ),
  'config' => 
  array (
    'size' => 20,
    'dir' => 'backup/20170108122710',
  ),
);