<?php 
\houdunwang\db\Db::table('hd_modules',true)->replace(array (
  'mid' => '1',
  'name' => 'basic',
  'industry' => 'business',
  'title' => '基本文字回复',
  'version' => '1.0',
  'resume' => '和您进行简单对话',
  'detail' => '一问一答得简单对话. 当访客的对话语句中包含指定关键字, 或对话语句完全等于特定关键字, 将回复文字或链接给用户',
  'author' => '后盾',
  'url' => 'http://open.hdcms.com',
  'is_system' => '1',
  'subscribes' => '',
  'processors' => 'a:1:{i:0;s:4:"text";}',
  'setting' => '0',
  'rule' => '0',
  'permissions' => '',
  'thumb' => 'thumb.jpg',
  'cover' => 'cover.jpg',
  'locality' => '1',
  'releaseCode' => '',
));
\houdunwang\db\Db::table('hd_modules',true)->replace(array (
  'mid' => '2',
  'name' => 'news',
  'industry' => 'business',
  'title' => '基本混合图文回复',
  'version' => '1.0',
  'resume' => '为你提供生动的图文资讯',
  'detail' => '一问一答得简单对话. 当访客的对话语句中包含指定关键字, 或对话语句完全等于特定关键字, 将回复文字或链接给用户',
  'author' => '后盾',
  'url' => 'http://open.hdcms.com',
  'is_system' => '1',
  'subscribes' => '',
  'processors' => 'a:1:{i:0;s:4:"text";}',
  'setting' => '0',
  'rule' => '0',
  'permissions' => '',
  'thumb' => 'thumb.jpg',
  'cover' => 'cover.jpg',
  'locality' => '1',
  'releaseCode' => '',
));
\houdunwang\db\Db::table('hd_modules',true)->replace(array (
  'mid' => '3',
  'name' => 'article',
  'industry' => 'business',
  'title' => '文章系统',
  'version' => '1.0',
  'resume' => '发布文章与会员中心管理',
  'detail' => '支持桌面、移动、微信三网的文章系统，同时具有移动、桌面会员中心管理功能',
  'author' => '后盾',
  'url' => 'http://open.hdcms.com',
  'is_system' => '1',
  'subscribes' => '',
  'processors' => '',
  'setting' => '0',
  'rule' => '0',
  'permissions' => '',
  'thumb' => 'thumb.jpg',
  'cover' => 'cover.jpg',
  'locality' => '1',
  'releaseCode' => '',
));
\houdunwang\db\Db::table('hd_modules',true)->replace(array (
  'mid' => '4',
  'name' => 'setting',
  'industry' => 'business',
  'title' => '网站配置',
  'version' => '1.0',
  'resume' => '网站运行整体配置',
  'detail' => '网站运行配置项，如支付、邮箱、登录等等的全局配置项管理',
  'author' => '后盾',
  'url' => 'http://open.hdcms.com',
  'is_system' => '1',
  'subscribes' => '',
  'processors' => '',
  'setting' => '0',
  'rule' => '0',
  'permissions' => '',
  'thumb' => 'thumb.jpg',
  'cover' => 'cover.jpg',
  'locality' => '1',
  'releaseCode' => '',
));
\houdunwang\db\Db::table('hd_modules',true)->replace(array (
  'mid' => '5',
  'name' => 'member',
  'industry' => 'business',
  'title' => '会员粉丝',
  'version' => '1.0',
  'resume' => '会员管理',
  'detail' => '会员与会员组管理，如会员字段，粉丝管理、会员卡设置',
  'author' => '后盾',
  'url' => 'http://open.hdcms.com',
  'is_system' => '1',
  'subscribes' => '',
  'processors' => '',
  'setting' => '0',
  'rule' => '0',
  'permissions' => '',
  'thumb' => 'thumb.jpg',
  'cover' => 'cover.jpg',
  'locality' => '1',
  'releaseCode' => '',
));
\houdunwang\db\Db::table('hd_modules',true)->replace(array (
  'mid' => '6',
  'name' => 'special',
  'industry' => 'business',
  'title' => '微信默认消息',
  'version' => '1.0',
  'resume' => '微信默认消息',
  'detail' => '系统默认消息与关注微信消息处理',
  'author' => '后盾',
  'url' => 'http://open.hdcms.com',
  'is_system' => '1',
  'subscribes' => '',
  'processors' => '',
  'setting' => '0',
  'rule' => '0',
  'permissions' => '',
  'thumb' => 'thumb.jpg',
  'cover' => 'cover.jpg',
  'locality' => '1',
  'releaseCode' => '',
));
\houdunwang\db\Db::table('hd_modules',true)->replace(array (
  'mid' => '7',
  'name' => 'ticket',
  'industry' => 'business',
  'title' => '卡券管理',
  'version' => '1.0',
  'resume' => '会员卡券管理',
  'detail' => '会员优惠券、代金券、实物券管理',
  'author' => '后盾',
  'url' => 'http://open.hdcms.com',
  'is_system' => '1',
  'subscribes' => '',
  'processors' => '',
  'setting' => '0',
  'rule' => '0',
  'permissions' => '',
  'thumb' => 'thumb.jpg',
  'cover' => 'cover.jpg',
  'locality' => '1',
  'releaseCode' => '',
));
\houdunwang\db\Db::table('hd_modules',true)->replace(array (
  'mid' => '8',
  'name' => 'cover',
  'industry' => 'business',
  'title' => '封面回复',
  'version' => '1.0',
  'resume' => '封面消息回复',
  'detail' => '用来处理模块的封面消息',
  'author' => '后盾',
  'url' => 'http://open.hdcms.com',
  'is_system' => '1',
  'subscribes' => '',
  'processors' => 'a:1:{i:0;s:4:"text";}',
  'setting' => '0',
  'rule' => '0',
  'permissions' => '',
  'thumb' => 'thumb.png',
  'cover' => 'cover.jpg',
  'locality' => '1',
  'releaseCode' => '',
));
\houdunwang\db\Db::table('hd_modules',true)->replace(array (
  'mid' => '9',
  'name' => 'uc',
  'industry' => 'business',
  'title' => '会员中心',
  'version' => '1.0',
  'resume' => '会员中心的管理操作',
  'detail' => '会员信息的管理，包括收货地址、个人资料、会员卡券等管理',
  'author' => '后盾',
  'url' => 'http://open.hdcms.com',
  'is_system' => '1',
  'subscribes' => '',
  'processors' => '',
  'setting' => '0',
  'rule' => '0',
  'permissions' => '',
  'thumb' => 'thumb.png',
  'cover' => 'cover.jpg',
  'locality' => '1',
  'releaseCode' => '',
));
\houdunwang\db\Db::table('hd_modules',true)->replace(array (
  'mid' => '10',
  'name' => 'button',
  'industry' => 'business',
  'title' => '微信菜单',
  'version' => '1.0',
  'resume' => '微信菜单管理',
  'detail' => '用于添加微信菜单，更新菜单后需要取消关注再关注或等微信更新缓存后有效',
  'author' => '后盾',
  'url' => 'http://open.hdcms.com',
  'is_system' => '1',
  'subscribes' => '',
  'processors' => '',
  'setting' => '0',
  'rule' => '0',
  'permissions' => '',
  'thumb' => 'thumb.jpg',
  'cover' => 'cover.jpg',
  'locality' => '1',
  'releaseCode' => '',
));
\houdunwang\db\Db::table('hd_modules',true)->replace(array (
  'mid' => '11',
  'name' => 'material',
  'industry' => 'business',
  'title' => '微信素材',
  'version' => '1.0',
  'resume' => '微信素材',
  'detail' => '公众号经常有需要用到一些临时性的多媒体素材的场景，例如在使用接口特别是发送消息时，对多媒体文件、多媒体消息的获取和调用等操作',
  'author' => '后盾',
  'url' => 'http://open.hdcms.com',
  'is_system' => '1',
  'subscribes' => '',
  'processors' => '',
  'setting' => '0',
  'rule' => '0',
  'permissions' => '',
  'thumb' => 'thumb.jpg',
  'cover' => 'cover.jpg',
  'locality' => '1',
  'releaseCode' => '',
));
