<?php 
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '1',
  'pid' => '0',
  'title' => '基础设置',
  'permission' => '',
  'url' => '?s=site/entry/home&p=platform',
  'append_url' => '',
  'icon' => 'fa fa-comments-o',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'platform',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '2',
  'pid' => '1',
  'title' => '基本功能',
  'permission' => '',
  'url' => '',
  'append_url' => '',
  'icon' => '',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'platform',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '3',
  'pid' => '2',
  'title' => '文字回复',
  'permission' => 'reply_basic',
  'url' => '?s=site/reply/lists&m=basic',
  'append_url' => '?s=site/reply/post&m=basic',
  'icon' => 'fa fa-plus',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'platform',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '21',
  'pid' => '0',
  'title' => '扩展模块',
  'permission' => '',
  'url' => '?s=site/entry/home&p=package',
  'append_url' => '',
  'icon' => 'fa fa-arrows',
  'orderby' => '100',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'package',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '27',
  'pid' => '21',
  'title' => '管理',
  'permission' => '',
  'url' => '',
  'append_url' => '',
  'icon' => '',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'package',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '30',
  'pid' => '2',
  'title' => '图文回复',
  'permission' => 'reply_news',
  'url' => '?s=site/reply/lists&m=news',
  'append_url' => '?s=site/reply/post&m=news',
  'icon' => 'fa fa-plus',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'platform',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '31',
  'pid' => '0',
  'title' => '功能选项',
  'permission' => '',
  'url' => '?s=site/entry/home&p=feature',
  'append_url' => '',
  'icon' => 'fa fa-comments-o',
  'orderby' => '20',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'feature',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '32',
  'pid' => '0',
  'title' => '会员粉丝',
  'permission' => '',
  'url' => '?s=site/entry/home&p=member',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '10',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'member',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '33',
  'pid' => '32',
  'title' => '会员中心',
  'permission' => '',
  'url' => '',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'member',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '35',
  'pid' => '33',
  'title' => '会员',
  'permission' => 'users',
  'url' => '?a=site/MemberLists&t=site&m=member',
  'append_url' => '?a=site/MemberPost&t=site&m=member',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'member',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '36',
  'pid' => '33',
  'title' => '会员组',
  'permission' => 'member_groups',
  'url' => '?a=site/GroupLists&t=site&m=member',
  'append_url' => '?a=site/GroupPost&t=site&m=member',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'member',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '38',
  'pid' => '32',
  'title' => '积分兑换',
  'permission' => '',
  'url' => '',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'member',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '39',
  'pid' => '38',
  'title' => '折扣券',
  'permission' => 'member_coupons',
  'url' => '?a=site/lists&t=site&type=1&m=ticket',
  'append_url' => '?a=site/post&t=site&type=1&m=ticket',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'member',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '40',
  'pid' => '38',
  'title' => '折扣券核销',
  'permission' => 'member_coupons_charge',
  'url' => '?a=site/charge&t=site&type=1&m=ticket',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'member',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '41',
  'pid' => '38',
  'title' => '代金券',
  'permission' => 'member_cash',
  'url' => '?a=site/lists&t=site&type=2&m=ticket',
  'append_url' => '?a=site/post&t=site&type=2&m=ticket',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'member',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '42',
  'pid' => '38',
  'title' => '代金券核销',
  'permission' => 'member_cash_charge',
  'url' => '?a=site/charge&t=site&type=2&m=ticket',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'member',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '55',
  'pid' => '2',
  'title' => '系统回复',
  'permission' => 'reply_special',
  'url' => '?a=site/post&t=site&m=special',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'platform',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '63',
  'pid' => '31',
  'title' => '公众号选项',
  'permission' => '',
  'url' => '',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'feature',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '64',
  'pid' => '63',
  'title' => '支付参数',
  'permission' => 'setting_pay',
  'url' => '?a=site/pay&t=site&m=setting',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'feature',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '66',
  'pid' => '31',
  'title' => '会员与粉丝选项',
  'permission' => '',
  'url' => '',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'feature',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '67',
  'pid' => '66',
  'title' => '积分设置',
  'permission' => 'setting_credit',
  'url' => '?a=site/credit&t=site&m=setting',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'feature',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '68',
  'pid' => '66',
  'title' => '注册设置',
  'permission' => 'setting_register',
  'url' => '?a=site/register&t=site&m=setting',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'feature',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '70',
  'pid' => '66',
  'title' => '邮件通知设置',
  'permission' => 'setting_mail',
  'url' => '?a=site/mail&t=site&m=setting',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'feature',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '71',
  'pid' => '0',
  'title' => '文章系统',
  'permission' => '',
  'url' => '?s=site/entry/home&p=article',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'article',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '72',
  'pid' => '71',
  'title' => '官网管理',
  'permission' => '',
  'url' => '?s=article/home/welcome',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'article',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '73',
  'pid' => '72',
  'title' => '官网模板',
  'permission' => 'article_manage_template',
  'url' => '?a=manage/template&t=site&m=article',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'article',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '74',
  'pid' => '71',
  'title' => '内容管理',
  'permission' => '',
  'url' => '',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'article',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '75',
  'pid' => '74',
  'title' => '分类管理',
  'permission' => 'article_content_category',
  'url' => '?a=content/category&t=site&m=article',
  'append_url' => '?a=content/categoryPost&t=site&m=article',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'article',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '76',
  'pid' => '74',
  'title' => '文章管理',
  'permission' => 'article_content_article',
  'url' => '?a=content/article&t=site&m=article',
  'append_url' => '?a=content/articlePost&t=site&m=article',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'article',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '77',
  'pid' => '72',
  'title' => '站点管理',
  'permission' => 'article_manage_site',
  'url' => '?a=manage/site&t=site&m=article',
  'append_url' => '?a=manage/SitePost&t=site&m=article',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'article',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '78',
  'pid' => '71',
  'title' => '特殊页面管理',
  'permission' => '',
  'url' => '',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'article',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '80',
  'pid' => '78',
  'title' => '会员中心',
  'permission' => 'article_ucenter_post',
  'url' => '?a=ucenter/post&t=site&m=article',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'article',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '81',
  'pid' => '27',
  'title' => '扩展功能管理',
  'permission' => 'package_managa',
  'url' => '?s=site/entry/package',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'package',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '82',
  'pid' => '1',
  'title' => '高级功能',
  'permission' => '',
  'url' => '',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'platform',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '84',
  'pid' => '33',
  'title' => '会员字段管理',
  'permission' => 'member_fields',
  'url' => '?a=site/Fieldlists&t=site&m=member',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'member',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '85',
  'pid' => '78',
  'title' => '微站快捷导航',
  'permission' => 'article_quick_menu',
  'url' => '?a=quickmenu/post&t=site&m=article',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'article',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '86',
  'pid' => '82',
  'title' => '微信菜单',
  'permission' => 'menus_lists',
  'url' => '?a=site/lists&t=site&m=button',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'platform',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '87',
  'pid' => '1',
  'title' => '微信素材',
  'permission' => '',
  'url' => '',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'platform',
));
\houdunwang\db\Db::table('hd_menu',true)->replace(array (
  'id' => '88',
  'pid' => '87',
  'title' => '素材&群发',
  'permission' => 'material',
  'url' => '?a=site/image&t=site&m=material',
  'append_url' => '',
  'icon' => 'fa fa-cubes',
  'orderby' => '0',
  'is_display' => '1',
  'is_system' => '1',
  'mark' => 'platform',
));
